name: First Workflow
on: workflow_dispatch #this will manually starts an workflow
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello world"
      - name: print goodbye
        run: echo "okay bye"
      
